title: Ibukun Alesinloye
subtitle: My Portfolio Website
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website built with ❤️❤️ using devlopr-jekyll. 

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Ibukun Alesinloye
author_bio: Experienced Software Developer with expertise in Back-End development and a passion for poetry. Proficient in several programming languages, including PHP, JavaScript, Python, and C. Specialized in utilizing various frameworks such as Laravel, NodeJS, and Express to build robust and scalable applications. Well-versed in Content Management Systems (CMS) like WordPress and WooCommerce. Extensive experience working with databases, including MySQL, MongoDB, and Firebase. Skilled in cloud platforms, including AWS, Google Cloud, and Digital Ocean, for deploying and managing applications in a scalable and efficient manner. Proficient in a variety of development tools such as Git, Docker, Postman, Visual Studio Code, Sublime Text, PHPStorm, PyCharm, and Android Studio. Constantly seeking to enhance skills and stay updated with the latest industry trends and technologies.
author_email: "hiibeekayvibe@gmail.com"
author_location: Abuja, Nigeria
author_website_url: "https://highb33kay.me"
author_resume_url: "https://drive.google.com/file/d/1HSRnItYiksiVfvrHWgU3hbOBuWhcip09/view?usp=sharing"
typewrite-text: Software Developer {BE} [ PHP | JS | Python | C ] [ Laravel | NodeJS | Express] [ WordPress ] [ Postgres | MySQL | MongoDB ] 
typewrite-body: FrameWorks  [ Laravel | NodeJS | Express ] {CMS} [ WordPress | WooCommerce ] {DB} [ MySQL | MongoDB | Firebase ] {Cloud} [ AWS | Google Cloud | Digital Ocean ] {Tools} [ Git | Docker | Postman | VSCode | Sublime Text | PHPStorm | PyCharm | Android Studio ]'
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Ziiko Solutions Ltd
              company_logo: ziiko_solutions_logo.jpeg
              company_url: https://ziikosolutions.com
              designation: Software Developer
              description: Worked on various diverse Software Products and Projects
              visibility: true
            - company_name: Zuri Team Inc
              company_logo: zuri_team_logo.jpeg
              company_url: https://zuri.team
              designation: Mentor
              description: Mentored Participants on the Zuri Internship Program
              visibility: true

# Education
author_education_details:
              - college_logo: university_of_abuja_logo.jpeg
                college_name: University of Abuja
                college_url: https://www.uniabuja.edu.ng/
                college_degree: Sociology
                description: Bachelor of Science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: Zuriportfolio.png
                project_title: Zuri Portfolio 
                project_description: A Portfolio Website built for Talents to Explore. Showcase. Sell. Connect. built with React, NextJS, TypeScript, NodeJS, Python, C#, TailwindCSS and Firebase
                project_url: https://zuriportfolio.vercel.app/
                visibility: true
              - project_thumbnail: Evento.png
                project_title: Evento
                project_description: A Web App for Event Management built with React, NextJS, TypeScript, NodeJS, TailwindCSS and Firebase
                project_url: https://evento1.vercel.app/
                visibility: true
              - project_thumbnail: Serjeants' Inn.png
                project_title: Serjeants' Inn Job Portal
                project_description: A Job Portal for Serjeants' Inn built with PHP, Elementor, WordPress and WooCommerce
                project_url: https://serjeantsinncareers.com/
                visibility: true
              - project_thumbnail: Tournament.png
                project_title: True Conservation Tournament WordPress Plugin
                project_description: A Custom WordPress Plugin for Tournament Management built with PHP, WordPress and WooCommerce
                project_url: https://true-conservation.org/
                visibility: true
              - project_thumbnail: Swish.png
                project_title: Swish Payment Gateway WordPress Plugin
                project_description: Custom Plugin Development for Swish for Handel Automatisk built with PHP, WordPress and WooCommerce
                project_url: https://redlight.se/produkt/swish-for-handel-automatisk
                visibility: true
              - project_thumbnail: Shell.jpeg
                project_title: A Custom Shell Project
                project_description: A Custom Shell Project built with C that mimics the Linux Shell
                project_url: https://github.com/highb33kay/simple_shell
                visibility: true
              - project_thumbnail: Mehnn.jpeg
                project_title: Mehnn - A Financial Analytical App Server
                project_description: A Financial Analytical App Server built with Laravel
                project_url: https://github.com/highb33kay/mehn
                visibility: true
              - project_thumbnail: Screen.png
                project_title: Screen Recorder Server built with NodeJS
                project_description: A Screen Recorder Server built with NodeJS, Express and Cloudinary
                project_url: https://github.com/highb33kay/ScreenRecordAPI
                visibility: true

# social links
twitter_username: highb33kay
github_username:  highb33kay
facebook_username: highb33kay
linkedin_username: ibukunalesinloye

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: highb33kay

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
# formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
